modLoader="javafml"
loaderVersion="[27,)"
issueTrackerURL="https://github.com/lumien231/QuickLeafDecay/issues"
displayURL="https://minecraft.curseforge.com/projects/fast-leaf-decay"

[[mods]]
    modId="quickleafdecay"
    version="${file.jarVersion}"
    authors="Lumien, JayJay1989be"
    credits="Thanks to MinecraftForge for providing the framework."
    displayName="Quick Leaf Decay"
    description='''
    Makes leaf decay faster

    Check the config to change the decay rate!
    '''

[[dependencies.quickleafdecay]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.quickleafdecay]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"