modLoader="javafml"
loaderVersion="[26,)"
logoFile="quickleafdecay.png" #optional
authors="Lumien" #optional
displayURL="https://minecraft.curseforge.com/projects/fast-leaf-decay" #optional
issueTrackerURL="https://github.com/lumien231/QuickLeafDecay" #optional

[[mods]]
    modId="quickleafdecay" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Quick Leaf Decay" #mandatory
    description='''
    Makes leaf decay faster

    Check the config to change the decay rate!
    '''

[[dependencies.sct]]
    modId="forge"
    mandatory=true
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"
